### Đăng nhập 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "phone": "0389804287",
    "password": "nguyenvan"
}

### Đăng nhập
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "phone": "0123456789",
    "password": "nguyenngoc"
}


### Lấy thông tin người dùng theo số điện thoại
GET http://localhost:3000/api/users/84389804287
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Ijg0MTIzNDU2Nzg5IiwiaWF0IjoxNzQ0NjQ0NjIyLCJleHAiOjE3NDQ3MzEwMjJ9.qz31ORZzy5MhBRPaaoAPj3tyC9GX82DiT-cdaCgqCn4

### Lấy lịch sử chat với 1 người nguyenngoc to nguyenvan
GET http://localhost:3000/api/chat/history/84389804287
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Ijg0MTIzNDU2Nzg5IiwiaWF0IjoxNzQ0NjQ0NjIyLCJleHAiOjE3NDQ3MzEwMjJ9.qz31ORZzy5MhBRPaaoAPj3tyC9GX82DiT-cdaCgqCn4

### Lấy lịch sử chat với 1 người nguyenvan to nguyenngoc
GET http://localhost:3000/api/chat/history/84123456789
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Ijg0Mzg5ODA0Mjg3IiwiaWF0IjoxNzQ0NjQ0NTcxLCJleHAiOjE3NDQ3MzA5NzF9.xWALjwly8sRkWfw2BbKin6NXUoANSOWVWNbb1x7Qttw

### lấy danh sách cuộc trò chuyện của người dùng đang đăng nhập
GET http://localhost:3000/api/chat/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Ijg0MTIzNDU2Nzg5IiwiaWF0IjoxNzQ0NjQ0NjIyLCJleHAiOjE3NDQ3MzEwMjJ9.qz31ORZzy5MhBRPaaoAPj3tyC9GX82DiT-cdaCgqCn4

// PHẦN TẠO TIN NHẮN SẼ ĐƯỢC LÀM Ở SOCKET-TEST.HTML
